name: Deploy Vite React App to Azure Static Web Apps

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  actions: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22  # ✅ You're using Node 22

      - name: Clean install workaround
        run: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
        working-directory: InventoryApp  # 🔁 adjust if needed

      - name: Build the Vite React app
        run: npm run build
        working-directory: InventoryApp

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "InventoryApp"
          output_location: "InventoryApp/dist"
